POST http://localhost:3000/api/services
Content-Type: application/json

{
      "name": "Decoração",
      "description": "Escolha a decoração para sua festa, e nós a montamos.",
      "price": 1400,
      "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}


###

GET http://localhost:3000/api/services


###
GET http://localhost:3000/api/services/66b3ce40e303861de2ad5c73


###
DELETE http://localhost:3000/api/services/66b3ce40e303861de2ad5c73


###
PUT http://localhost:3000/api/services/66b3ce40e303861de2ad5c77
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Alguma descrição",
    "price": 2500,
    "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM="
}


###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Rafael",
    "description": "Despedida de solteiro",
    "budget": 10000,
    "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM=",
    "services": [
        {
          "name": "Algum serviço 1",
          "description": "Alguma descrição",
          "price": 6500,
          "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM="  
        },

        {
          "name": "Algum serviço",
          "description": "Alguma descrição",
          "price": 2500,
          "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM="  
        }
    ] 
}


###
GET http://localhost:3000/api/parties


###
GET http://localhost:3000/api/parties/66bbc3a9562dc5892754cd6f


###
DELETE http://localhost:3000/api/parties/66bbc4fd562dc5892754cd71


###
PUT http://localhost:3000/api/parties/66bbc3a9562dc5892754cd6f
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Rafael",
    "description": "Despedida de solteiro",
    "budget": 10000,
    "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM=",
    "services": [
        {
          "name": "Algum serviço 1",
          "description": "Alguma descrição",
          "price": 6500,
          "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM=",  
        },

        {
          "name": "Algum serviço",
          "description": "Alguma descrição",
          "price": 2500,
          "image": "https://media.istockphoto.com/id/1077832058/pt/foto/colorful-balloons-floating-in-the-sky-at-sunset.jpg?s=1024x1024&w=is&k=20&c=ut-kmQcWjSdkyEWcMMG10vOIETQ15AGTtY8bZc41iFM=",  
        }
    ] 
}